apiVersion: v1
kind: Pod
metadata:
  name: movie_api
  labels:
    app: movie
spec:
  containers:
   - name: flask-mov2
     image: alvin89/flask-mov:7.0
     ports:
     - containerPort: 31212
---
apiVersion: v1
kind: Service
metadata:
  name: movie_api
spec:
  type: NodePort
  selector:
    app: movie
  ports:
   - name: flask
     port: 31111
     protocol: TCP
     targetPort: 31212
     nodePort: 31111
