apiVersion: v1
kind: Pod
metadata:
  name: movie
  labels:
    app: movie
spec:
  containers:
   - name: flask-mov2
     image: alvin89/flask-mov:7.0
     ports:
     - containerPort: 31212
   - name: nginx-ui
     image: alvin89/nginx-ui:13.0
     ports:
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: movie
spec:
  type: NodePort
  selector:
    app: movie
  ports:
   - name: flask
     port: 31111
     protocol: TCP
     targetPort: 31212
     nodePort: 31111
   - name: nginx
     port: 32222
     protocol: TCP
     targetPort: 80
     nodePort: 32222
